# Generated by Django 5.2.9 on 2026-02-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="google_maps_link",
            field=models.URLField(
                blank=True,
                help_text="Google Maps link for the event location",
                max_length=500,
            ),
        ),
    ]
