from enum import Enum

class UserRoles(Enum):
    SUPER_SYSTEM_ADMIN = 'SUPER_SYSTEM_ADMIN'
    SUPER_ADMIN = 'SUPER_ADMIN'
    ADMIN = 'ADMIN'
    FINANCE_ADMIN = 'FINANCE_ADMIN'
    ATTENDANCE_OFFICER = 'ATTENDANCE_OFFICER'
    MEMBER = 'MEMBER'

