# Generated by Django 5.2.9 on 2026-01-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="code",
            field=models.CharField(blank=True, db_index=True, max_length=4, null=True),
        ),
    ]
