# Generated by Django 5.2.9 on 2026-01-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_organization_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="code",
            field=models.CharField(db_index=True, max_length=4, unique=True),
        ),
    ]
