# Generated by Django 5.2.9 on 2026-02-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_contactgroup_contact"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contactgroup",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="contactgroup",
            name="organization",
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.DeleteModel(
            name="ContactGroup",
        ),
    ]
