# Generated by Django 5.2.9 on 2026-01-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("admin", "Admin"),
                    ("finance_admin", "Finance Admin"),
                    ("attendance_officer", "Attendance Officer"),
                    ("treasurer", "Treasurer"),
                    ("member", "Member"),
                ],
                default="member",
                max_length=50,
            ),
        ),
    ]
