# Generated by Django 5.2.9 on 2026-01-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_user_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="filled_form",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user has completed their profile after registration.",
            ),
        ),
    ]
