# Generated by Django 5.2.9 on 2026-01-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_add_filled_form_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, help_text="Home address"),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, help_text="Date of birth", null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="denomination",
            field=models.CharField(
                blank=True, help_text="Religious denomination", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_contact_name",
            field=models.CharField(
                blank=True, help_text="Emergency contact full name", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True, help_text="Emergency contact phone number", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_contact_relationship",
            field=models.CharField(
                blank=True,
                help_text="Relationship to emergency contact (e.g., spouse, parent, sibling)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="employer",
            field=models.CharField(
                blank=True, help_text="Employer or institution name", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="employment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("employed", "Employed"),
                    ("self_employed", "Self Employed"),
                    ("student", "Student"),
                    ("unemployed", "Unemployed"),
                    ("retired", "Retired"),
                ],
                help_text="Current employment status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                help_text="Gender of the member",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="join_date",
            field=models.DateField(
                blank=True, help_text="Date the member joined the choir", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="member_part",
            field=models.CharField(
                blank=True,
                choices=[
                    ("soprano", "Soprano"),
                    ("alto", "Alto"),
                    ("tenor", "Tenor"),
                    ("bass", "Bass"),
                ],
                help_text="Voice part in the choir",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="occupation",
            field=models.CharField(
                blank=True, help_text="Occupation or profession", max_length=100
            ),
        ),
    ]
