# Generated by Django 5.2.9 on 2026-01-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_add_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='member_part',
            field=models.CharField(blank=True, choices=[('soprano', 'Soprano'), ('alto', 'Alto'), ('tenor', 'Tenor'), ('bass', 'Bass'), ('instrumentalist', 'Instrumentalist'), ('directorate', 'Directorate')], help_text='Voice part in the choir', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('finance_admin', 'Finance Admin'), ('attendance_officer', 'Attendance Officer'), ('treasurer', 'Treasurer'), ('part_leader', 'Part Leader'), ('member', 'Member')], default='member', max_length=50),
        ),
    ]
