# Generated by Django 5.2.9 on 2026-02-01 14:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_member_part_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target', models.CharField(help_text='Email or Phone number', max_length=255)),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('activation', 'Account Activation'), ('password_reset', 'Password Reset'), ('login', 'Login Verification')], default='activation', max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'otps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target', 'purpose'], name='otps_target_a708fd_idx')],
            },
        ),
    ]
