# Generated by Django 5.2.9 on 2026-05-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("activation", "Account Activation"),
                    ("password_reset", "Password Reset"),
                    ("login", "Login Verification"),
                    ("wallet_verification", "Wallet Verification"),
                ],
                default="activation",
                max_length=20,
            ),
        ),
    ]
