# Generated by Django 5.2.9 on 2026-05-12 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="mobilewallet",
            new_name="mobile_wall_user_id_e172ec_idx",
            old_name="mobile_wall_user_id_d3ef80_idx",
        ),
        migrations.RenameIndex(
            model_name="mobilewallet",
            new_name="mobile_wall_account_a3357d_idx",
            old_name="mobile_wall_account_0bb9d2_idx",
        ),
    ]
