# Generated by Django 5.2.9 on 2026-06-04 17:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "wallet",
            "0002_rename_mobile_wall_user_id_d3ef80_idx_mobile_wall_user_id_e172ec_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mobilewallet",
            unique_together={("user", "account_number")},
        ),
    ]
