# Generated by Django 5.2.9 on 2026-01-02 23:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("fully_paid", "Pending Payment"),
                    ("partially_paid", "Active"),
                    ("overdue", "Overdue"),
                    ("not_paid", "Not Paid"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "checkout_id",
                    models.CharField(
                        blank=True,
                        help_text="Hubtel's checkout ID from initiate response",
                        max_length=255,
                    ),
                ),
                (
                    "client_reference",
                    models.CharField(
                        db_index=True,
                        help_text="Our unique reference for this transaction (max 32 chars per Hubtel)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "hubtel_transaction_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Hubtel's internal transaction ID (from callback)",
                        max_length=255,
                    ),
                ),
                (
                    "network_transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Mobile network's transaction ID (externalTransactionId)",
                        max_length=255,
                    ),
                ),
                (
                    "sales_invoice_id",
                    models.CharField(
                        blank=True,
                        help_text="Hubtel's SalesInvoiceId from callback",
                        max_length=255,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount for this specific payment attempt",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="GHS",
                        help_text="Currency code (GHS, USD, etc.)",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Payment Initiated"),
                            ("pending", "Pending Confirmation"),
                            ("success", "Payment Successful"),
                            ("failed", "Payment Failed"),
                            ("expired", "Payment Expired"),
                            ("cancelled", "Payment Cancelled"),
                            ("refunded", "Payment Refunded"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                (
                    "checkout_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to redirect user to Hubtel checkout",
                        max_length=500,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Payment description shown to user", max_length=255
                    ),
                ),
                (
                    "payment_channel",
                    models.CharField(
                        blank=True,
                        help_text="e.g., mtn-gh, vodafone-gh, card",
                        max_length=50,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        blank=True, help_text="e.g., mobilemoney, card", max_length=50
                    ),
                ),
                (
                    "customer_mobile_number",
                    models.CharField(
                        blank=True,
                        help_text="Customer's mobile number used for payment",
                        max_length=20,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True,
                        help_text="Customer name from payment provider",
                        max_length=255,
                    ),
                ),
                (
                    "charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Transaction charges/fees from Hubtel",
                        max_digits=10,
                    ),
                ),
                (
                    "amount_after_charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount after charges deduction",
                        max_digits=10,
                    ),
                ),
                (
                    "initiated_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When payment was initiated"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When payment was confirmed/completed",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this payment attempt expires (5 mins from initiation)",
                        null=True,
                    ),
                ),
                (
                    "callback_received_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When we received Hubtel's callback",
                        null=True,
                    ),
                ),
                (
                    "callback_data",
                    models.JSONField(
                        blank=True,
                        help_text="Raw callback data from Hubtel for debugging",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if payment failed"
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0, help_text="Number of times user retried this payment"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional metadata (IP address, user agent, etc.)",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Admin notes about this transaction"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Denormalized for multi-tenant queries",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="core.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Denormalized for quick queries",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_subscription",
                    models.ForeignKey(
                        help_text="The user subscription this payment is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="subscriptions.usersubscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Transaction",
                "verbose_name_plural": "Payment Transactions",
                "db_table": "payment_transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_subscription", "status"],
                        name="payment_tra_user_su_92c37b_idx",
                    ),
                    models.Index(
                        fields=["user", "status"], name="payment_tra_user_id_131e27_idx"
                    ),
                    models.Index(
                        fields=["organization", "status"],
                        name="payment_tra_organiz_6bf441_idx",
                    ),
                    models.Index(
                        fields=["client_reference"],
                        name="payment_tra_client__6fbf69_idx",
                    ),
                    models.Index(
                        fields=["hubtel_transaction_id"],
                        name="payment_tra_hubtel__13f0e8_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="payment_tra_status_ea288f_idx",
                    ),
                    models.Index(
                        fields=["initiated_at"], name="payment_tra_initiat_02d485_idx"
                    ),
                    models.Index(
                        fields=["confirmed_at"], name="payment_tra_confirm_4f9388_idx"
                    ),
                ],
            },
        ),
    ]
