# Generated by Django 5.2.9 on 2026-06-05 15:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_fix_usersubscription_status_defaults"),
        ("wallet", "0003_alter_mobilewallet_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectDebit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount to be debited from the wallet",
                        max_digits=10,
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "DAILY"),
                            ("WEEKLY", "WEEKLY"),
                            ("MONTHLY", "MONTHLY"),
                            ("QUARTERLY", "QUARTERLY"),
                            ("ANNUALLY", "ANNUALLY"),
                        ],
                        default="MONTHLY",
                        max_length=20,
                    ),
                ),
                (
                    "next_payment_date",
                    models.DateField(
                        blank=True,
                        help_text="Next payment date for this direct debit",
                        null=True,
                    ),
                ),
                (
                    "previous_payment_date",
                    models.DateField(
                        blank=True,
                        help_text="Previous payment date for this direct debit",
                        null=True,
                    ),
                ),
                ("hubtel_preapproval_id", models.CharField(blank=True, max_length=255)),
                (
                    "initiate_client_reference",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("otp_prefix", models.CharField(blank=True, max_length=10)),
                ("approval_status", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="direct_debits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="direct_debits",
                        to="subscriptions.usersubscription",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="direct_debits",
                        to="wallet.mobilewallet",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
