# Generated by Django 5.2.9 on 2026-06-05 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_directdebit"),
        ("wallet", "0003_alter_mobilewallet_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="directdebit",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Direct Debit",
                "verbose_name_plural": "Direct Debits",
            },
        ),
        migrations.AddIndex(
            model_name="directdebit",
            index=models.Index(
                fields=["user", "is_active"], name="direct_debi_user_id_546744_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="directdebit",
            index=models.Index(
                fields=["approval_status", "next_payment_date"],
                name="direct_debi_approva_0bf830_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="directdebit",
            index=models.Index(
                fields=["next_payment_date"], name="direct_debi_next_pa_e8f11b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="directdebit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("user_subscription",),
                name="uniq_active_dd_per_user_sub",
            ),
        ),
        migrations.AlterModelTable(
            name="directdebit",
            table="direct_debits",
        ),
    ]
