# Generated by Django 5.2.9 on 2026-06-09 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_alter_directdebit_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="direct_debit",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this transaction is an automated direct-debit charge",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_transactions",
                to="subscriptions.directdebit",
            ),
        ),
    ]
