# Generated by Django 5.2.9 on 2026-06-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0006_paymenttransaction_direct_debit"),
    ]

    operations = [
        migrations.AddField(
            model_name="directdebit",
            name="consecutive_failed_charges",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Consecutive failed charge attempts; the mandate is deactivated at the cap.",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="checkout_id",
            field=models.CharField(
                blank=True,
                help_text="Hubtel's checkout ID from initiate response",
                max_length=255,
                null=True,
            ),
        ),
    ]
