# Generated by Django 5.2.9 on 2026-01-29 19:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_organization_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Event title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Event description')),
                ('event_type', models.CharField(choices=[('rehearsal', 'Rehearsal'), ('funeral', 'Funeral'), ('wedding', 'Wedding'), ('corporate', 'Corporate Event'), ('concert', 'Concert'), ('church_service', 'Church Service'), ('other', 'Other')], default='rehearsal', help_text='Type of event', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Event location', max_length=255)),
                ('start_datetime', models.DateTimeField(help_text='Event start date and time')),
                ('end_datetime', models.DateTimeField(blank=True, help_text='Event end date and time (optional)', null=True)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Whether attendance is mandatory for this event')),
                ('target_voice_parts', models.JSONField(blank=True, help_text="List of voice parts this event is targeted at (e.g., ['soprano', 'alto']). Null means all parts.", null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', help_text='Current status of the event', max_length=20)),
                ('created_by', models.ForeignKey(help_text='User who created this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'events',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused'), ('late', 'Late')], default='absent', help_text='Attendance status', max_length=20)),
                ('marked_at', models.DateTimeField(auto_now_add=True, help_text='When the attendance was marked')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this attendance record')),
                ('event', models.ForeignKey(help_text='The event this attendance record is for', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.event')),
                ('marked_by', models.ForeignKey(help_text='User who marked this attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The member whose attendance is being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Attendance',
                'verbose_name_plural': 'Event Attendances',
                'db_table': 'event_attendances',
                'ordering': ['-marked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'status'], name='events_organiz_44b951_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'event_type'], name='events_organiz_bd50ac_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_datetime'], name='events_start_d_2ddaa0_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'start_datetime'], name='events_organiz_c4281a_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendance',
            index=models.Index(fields=['event', 'status'], name='event_atten_event_i_946a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendance',
            index=models.Index(fields=['user', 'status'], name='event_atten_user_id_09cbd3_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendance',
            index=models.Index(fields=['marked_at'], name='event_atten_marked__23eee7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventattendance',
            unique_together={('event', 'user')},
        ),
    ]
