# Generated by Django 5.2.9 on 2026-01-29 21:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused'), ('late', 'Late')], default='absent', help_text='Attendance status', max_length=20)),
                ('marked_at', models.DateTimeField(auto_now_add=True, help_text='When the attendance was marked')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this attendance record')),
                ('event', models.ForeignKey(help_text='The event this attendance record is for', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.event')),
                ('marked_by', models.ForeignKey(help_text='User who marked this attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The member whose attendance is being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Attendance',
                'verbose_name_plural': 'Event Attendances',
                'db_table': 'event_attendances',
                'ordering': ['-marked_at'],
                'indexes': [models.Index(fields=['event', 'status'], name='event_atten_event_i_946a2f_idx'), models.Index(fields=['user', 'status'], name='event_atten_user_id_09cbd3_idx'), models.Index(fields=['marked_at'], name='event_atten_marked__23eee7_idx')],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
